import {Raleway} from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata = {
  title: "Sort Options",
  description: "Generated by create next app. Kramstyles",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} font-raleway`}
      >
        {children}
      </body>
    </html>
  );
}
